---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerlift
  labels:
    app: careerlift
spec:
  replicas: 3
  selector:
    matchLabels:
      app: careerlift
  template:
    metadata:
      labels:
        app: careerlift
    spec:
      imagePullSecrets:
      - name: nexus-registry-credentials

      containers:
      - name: careerlift
        image: 127.0.0.1:30085/careerlift/careerlift-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        env:
        - name: DEBUG
          value: "1"

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: career-secret
              key: secret-key

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: career-secret
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: career-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: career-secret
              key: DB_PASSWORD

        - name: DB_HOST
          value: "careerlift-mysql"

        - name: DB_PORT
          value: "3306"

        - name: DATABASE_URL
          value: "mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: careerlift-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: careerlift

---
apiVersion: v1
kind: Service
metadata:
  name: careerlift-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: careerlift-mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
