apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "2401185"
type: Opaque
data:
  root-password: YWRtaW4xMjM=  # base64 for 'admin123'
  username: Y2FyZWVybGlmdA==  # base64 for 'careerlift'
  password: cGFzc3dvcmQxMjM=  # base64 for 'password123'
  database: Y2FyZWVybGlmdF9kYg==  # base64 for 'careerlift_db'
